name: ServerWarp
main: me.krotn.ServerWarp.ServerWarp
version: 0.1
author: Krotn
commands:
    listwarps:
        description: Lists all public warps.
        permission: ServerWarp.warp.list
        usage: |
          /listwarps
    setwarp:
        description: Sets a new public warp at your current location.
        permission: ServerWarp.warp.set
        usage: /setwarp [name]
    warp:
        description: Moves the player to a warp.
        permission: ServerWarp.warp
        usage: /warp [name]

permissions:
    ServerWarp.warp.list:
        default: true
        description: Allows the player to see a list of warps.
    ServerWarp.warp.set:
        default: op
        description: Allows the player to set new public warps.
    ServerWarp.warp:
        default: true
        description: Allows the player to use public warps.
    ServerWarp.motion.depart:
        default: true
        description: Allows the player to leave using tp, warp or waypoint.
    ServerWarp.motion.arrive:
        default: true
        description: Allows the player to arrive using tp, warp or waypoint.